### PR TITLE
Task Management Completed

### PR DESCRIPTION
**Pull request by haq-intekhab**
This PR implements a feature to filter tasks based on their completion status and group. It ensures tasks are marked as completed correctly and updates the task list accordingly.

Screenshot 2024-08-05 155200
Screenshot 2024-08-05 155221
Screenshot 2024-08-05 155242

https://github.com/user-attachments/assets/107f8b15-e202-444b-a385-1996b659ab67

Implemented a filtering mechanism to display tasks by their completion status and group.
Updated the markAsCompleted function to refresh the task list after a task is marked as completed.
Refactored the TaskList component to categorize tasks into pending, in-progress, and completed sections.
Enhanced the UI of task cards to reflect the task status accurately.
Implementation Details
TaskList Component: Refactored the component to categorize tasks into three sections: pending, in-progress, and completed.

Used a currentGroup state to track the active group of tasks.
Filtered tasks based on their completion status and group using filteredTasks for in-progress tasks and incompleteTasks for pending tasks.
Updated the UI to display tasks under their respective categories.
Mark As Completed: Improved the markAsCompleted function to:

Send a PUT request to update the task's status on the server.
Update the local state to reflect the change.
Recalculate the currentGroup based on completed tasks to ensure sequential task unlocking.
UI Enhancements: Updated task cards to visually indicate their status.

Added a "Done" button to mark tasks as completed, only enabled for in-progress tasks.
Displayed task counts for each category to provide a clear overview.

### CODE REVIEW

**Comment by redhatpanda** [comment]
Hi @haq-intekhab your build is failing. Please make sure the Pull Request Validation build successfully runs
image

**Comment by swapnanilrayCL** [comment]
Hi @haq-intekhab your build is failing. Please make sure the Pull Request Validation build successfully runs
image

**Comment by s7arborne** [comment]
Could you explain the reason why you changed the folder structure of the entire repo? It was in the web folder

**Comment by haq-intekhab** [comment]
> Could you explain the reason why you changed the folder structure of the entire repo? It was in the web folder
 it was my mistake i will fix it and push the required structure

**Comment by haq-intekhab** [comment]
Screenshot (3)
build has been successfull and i have also made the folder structure right ? do i need to make a pull request again @s7arborne

**Comment by haq-intekhab** [comment]
> > Screenshot (3) build has been successfull and i have also made the folder structure right ? do i need to make a pull request again @s7arborne
> 
> make a commit. You don't need to make another PR for it
I have  made a commit please check @s7arborne

**Comment by s7arborne** [comment]
> > > Screenshot (3) build has been successfull and i have also made the folder structure right ? do i need to make a pull request again @s7arborne
> > 
> > 
> > make a commit. You don't need to make another PR for it
> > I have  made a commit please check @s7arborne
You have not actually,
image
Your last commit was 7 hours ago

**Comment by haq-intekhab** [comment]
> > > > Screenshot (3) build has been successfull and i have also made the folder structure right ? do i need to make a pull request again @s7arborne
> > > 
> > > 
> > > make a commit. You don't need to make another PR for it
> > > I have  made a commit please check @s7arborne
> > > You have not actually,
> > > image
> > > Your last commit was 7 hours ago

Screenshot (4)
i have made the commit 1 hour ago @s7arborne  you can see

**Comment by haq-intekhab** [comment]
> > > > > > Screenshot (3) build has been successfull and i have also made the folder structure right ? do i need to make a pull request again @s7arborne
> > > > > 
> > > > > 
> > > > > make a commit. You don't need to make another PR for it
> > > > > I have  made a commit please check @s7arborne
> > > > > You have not actually,
> > > > > image
> > > > > Your last commit was 7 hours ago
> > 
> > 
> > Screenshot (4) i have made the commit 1 hour ago @s7arborne you can see
> 
> You may need to sync the fork

i have synced the fork @s7arborne please check it

**Comment by s7arborne** [comment]
> > > > > > > Screenshot (3) build has been successfull and i have also made the folder structure right ? do i need to make a pull request again @s7arborne
> > > > > > 
> > > > > > 
> > > > > > make a commit. You don't need to make another PR for it
> > > > > > I have  made a commit please check @s7arborne
> > > > > > You have not actually,
> > > > > > image
> > > > > > Your last commit was 7 hours ago
> > > 
> > > 
> > > Screenshot (4) i have made the commit 1 hour ago @s7arborne you can see
> > 
> > 
> > You may need to sync the fork
> 
> i have synced the fork @s7arborne please check it

I see the problem now. You made the changes in another branch. So you need to make another PR from the main branch, this is your master branch's PR. Make a fresh PR from your main branch

**Comment by haq-intekhab** [comment]
Done @s7arborne

**Pull request closed without merging**
